### ISSUE TITLE
Icons disappearing 

### ISSUE THREAD

**Issue by PapaDocta** [mapaction/ocha-humanitarian-icons-for-gis#1]
some icons disappears when exporting pdf from arcgis under windows 10....

**Comment by macsims1** [comment]
When you exported the map in ArcGIS did you make sure "Embed All Document Fonts" is ticked.

![image](https://user-images.githubusercontent.com/5641143/32832330-0379db92-c9f3-11e7-83b4-36a43440074a.png)

**Comment by PapaDocta** [comment]
Thanks macsims1 for your reply... and yes the embed all document fonts is ticked. If I un-tick it, a different set of icons appears instead of the ones I specified in arcgis. also this happens when i export to AI as well.
i'm using arcgis 10.5.1

edit
this is the properties of the pdf files regarding the fonts
https://ibb.co/m4h27m

**Comment by PapaDocta** [comment]
any fix for this issue?
